name: badges
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  badges:
    name: create badges
    runs-on: ubuntu-latest
    if: github.repository == 'hoofpilot/hoofpilot'
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - run: |
        sudo chmod +x tools/setup_dependencies.sh
        ./tools/op.sh setup
    - name: Push badges
      run: |
        python3 selfdrive/ui/translations/create_badges.py

        rm .gitattributes

        git checkout --orphan badges
        git rm -rf --cached .
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "Badge Researcher"

        git add translation_badge.svg
        git commit -m "Add/Update badges"
        git push -f origin HEAD
